# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pyCharm\project\UI\RectPrismModelSettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RectPrismModelSettingDialog(object):
    def setupUi(self, RectPrismModelSettingDialog):
        RectPrismModelSettingDialog.setObjectName("RectPrismModelSettingDialog")
        RectPrismModelSettingDialog.resize(518, 331)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/UI/dialogLogo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RectPrismModelSettingDialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(RectPrismModelSettingDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(RectPrismModelSettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(180, 0))
        self.widget.setStyleSheet("image: url(:/UI/Resources/CubeInput.png);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(RectPrismModelSettingDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.centerX = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerX.sizePolicy().hasHeightForWidth())
        self.centerX.setSizePolicy(sizePolicy)
        self.centerX.setObjectName("centerX")
        self.gridLayout.addWidget(self.centerX, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.centerY = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerY.sizePolicy().hasHeightForWidth())
        self.centerY.setSizePolicy(sizePolicy)
        self.centerY.setObjectName("centerY")
        self.gridLayout.addWidget(self.centerY, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.Length = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Length.sizePolicy().hasHeightForWidth())
        self.Length.setSizePolicy(sizePolicy)
        self.Length.setObjectName("Length")
        self.gridLayout.addWidget(self.Length, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.Height = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Height.sizePolicy().hasHeightForWidth())
        self.Height.setSizePolicy(sizePolicy)
        self.Height.setObjectName("Height")
        self.gridLayout.addWidget(self.Height, 5, 1, 1, 1)
        self.centerZ = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerZ.sizePolicy().hasHeightForWidth())
        self.centerZ.setSizePolicy(sizePolicy)
        self.centerZ.setObjectName("centerZ")
        self.gridLayout.addWidget(self.centerZ, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.Width = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Width.sizePolicy().hasHeightForWidth())
        self.Width.setSizePolicy(sizePolicy)
        self.Width.setObjectName("Width")
        self.gridLayout.addWidget(self.Width, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(RectPrismModelSettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(210, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelProperty = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProperty.sizePolicy().hasHeightForWidth())
        self.labelProperty.setSizePolicy(sizePolicy)
        self.labelProperty.setMinimumSize(QtCore.QSize(66, 0))
        self.labelProperty.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProperty.setObjectName("labelProperty")
        self.horizontalLayout_2.addWidget(self.labelProperty)
        self.property = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.property.sizePolicy().hasHeightForWidth())
        self.property.setSizePolicy(sizePolicy)
        self.property.setObjectName("property")
        self.horizontalLayout_2.addWidget(self.property)
        self.labelUnit = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUnit.sizePolicy().hasHeightForWidth())
        self.labelUnit.setSizePolicy(sizePolicy)
        self.labelUnit.setObjectName("labelUnit")
        self.horizontalLayout_2.addWidget(self.labelUnit)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_OK = QtWidgets.QPushButton(RectPrismModelSettingDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/UI/apply"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_OK.setIcon(icon1)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout.addWidget(self.pushButton_OK)
        self.pushButton_Cancel = QtWidgets.QPushButton(RectPrismModelSettingDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/UI/cancel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Cancel.setIcon(icon2)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(RectPrismModelSettingDialog)
        self.pushButton_OK.clicked.connect(RectPrismModelSettingDialog.accept)
        self.pushButton_Cancel.clicked.connect(RectPrismModelSettingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RectPrismModelSettingDialog)
        RectPrismModelSettingDialog.setTabOrder(self.centerX, self.centerY)
        RectPrismModelSettingDialog.setTabOrder(self.centerY, self.centerZ)
        RectPrismModelSettingDialog.setTabOrder(self.centerZ, self.Length)
        RectPrismModelSettingDialog.setTabOrder(self.Length, self.Width)
        RectPrismModelSettingDialog.setTabOrder(self.Width, self.Height)
        RectPrismModelSettingDialog.setTabOrder(self.Height, self.property)
        RectPrismModelSettingDialog.setTabOrder(self.property, self.pushButton_OK)
        RectPrismModelSettingDialog.setTabOrder(self.pushButton_OK, self.pushButton_Cancel)

    def retranslateUi(self, RectPrismModelSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        RectPrismModelSettingDialog.setWindowTitle(_translate("RectPrismModelSettingDialog", "长方体模型参数设置"))
        self.groupBox.setTitle(_translate("RectPrismModelSettingDialog", "几何参数"))
        self.label_7.setText(_translate("RectPrismModelSettingDialog", "中心坐标(x)"))
        self.centerX.setText(_translate("RectPrismModelSettingDialog", "4"))
        self.label_8.setText(_translate("RectPrismModelSettingDialog", "中心坐标(y)"))
        self.centerY.setText(_translate("RectPrismModelSettingDialog", "4"))
        self.label_14.setText(_translate("RectPrismModelSettingDialog", "宽度(w)"))
        self.Length.setText(_translate("RectPrismModelSettingDialog", "2"))
        self.label_13.setText(_translate("RectPrismModelSettingDialog", "高度(h)"))
        self.label_9.setText(_translate("RectPrismModelSettingDialog", "中心坐标(z)"))
        self.Height.setText(_translate("RectPrismModelSettingDialog", "2"))
        self.centerZ.setText(_translate("RectPrismModelSettingDialog", "4"))
        self.label_6.setText(_translate("RectPrismModelSettingDialog", "长度(l)"))
        self.Width.setText(_translate("RectPrismModelSettingDialog", "2"))
        self.label.setText(_translate("RectPrismModelSettingDialog", "（埋深，z轴向下为正）"))
        self.label_2.setText(_translate("RectPrismModelSettingDialog", "（南北方向）"))
        self.label_3.setText(_translate("RectPrismModelSettingDialog", "（东西方向）"))
        self.label_4.setText(_translate("RectPrismModelSettingDialog", "（垂直方向）"))
        self.groupBox_2.setTitle(_translate("RectPrismModelSettingDialog", "物性参数"))
        self.labelProperty.setText(_translate("RectPrismModelSettingDialog", "物性"))
        self.property.setText(_translate("RectPrismModelSettingDialog", "1"))
        self.labelUnit.setText(_translate("RectPrismModelSettingDialog", "g/cm^3"))
        self.pushButton_OK.setText(_translate("RectPrismModelSettingDialog", "确定"))
        self.pushButton_Cancel.setText(_translate("RectPrismModelSettingDialog", "取消"))

import UI.UI_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RectPrismModelSettingDialog = QtWidgets.QDialog()
    ui = Ui_RectPrismModelSettingDialog()
    ui.setupUi(RectPrismModelSettingDialog)
    RectPrismModelSettingDialog.show()
    sys.exit(app.exec_())

