# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pyCharm\project\UI\SphereModelSettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SphereModelSettingDialog(object):
    def setupUi(self, SphereModelSettingDialog):
        SphereModelSettingDialog.setObjectName("SphereModelSettingDialog")
        SphereModelSettingDialog.resize(461, 197)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/UI/dialogLogo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SphereModelSettingDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(SphereModelSettingDialog)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(SphereModelSettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("image: url(:/UI/Resources/SphereInput.png);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.centerZ = QtWidgets.QLineEdit(SphereModelSettingDialog)
        self.centerZ.setObjectName("centerZ")
        self.gridLayout.addWidget(self.centerZ, 2, 1, 1, 1)
        self.labelUnit = QtWidgets.QLabel(SphereModelSettingDialog)
        self.labelUnit.setObjectName("labelUnit")
        self.gridLayout.addWidget(self.labelUnit, 4, 2, 1, 1)
        self.property = QtWidgets.QLineEdit(SphereModelSettingDialog)
        self.property.setObjectName("property")
        self.gridLayout.addWidget(self.property, 4, 1, 1, 1)
        self.labelProperty = QtWidgets.QLabel(SphereModelSettingDialog)
        self.labelProperty.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProperty.setObjectName("labelProperty")
        self.gridLayout.addWidget(self.labelProperty, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(SphereModelSettingDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(SphereModelSettingDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SphereModelSettingDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.centerY = QtWidgets.QLineEdit(SphereModelSettingDialog)
        self.centerY.setObjectName("centerY")
        self.gridLayout.addWidget(self.centerY, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.centerX = QtWidgets.QLineEdit(SphereModelSettingDialog)
        self.centerX.setObjectName("centerX")
        self.gridLayout.addWidget(self.centerX, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(SphereModelSettingDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.radius = QtWidgets.QLineEdit(SphereModelSettingDialog)
        self.radius.setObjectName("radius")
        self.gridLayout.addWidget(self.radius, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(SphereModelSettingDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.okButton = QtWidgets.QPushButton(SphereModelSettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/UI/apply"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon1)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(SphereModelSettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/UI/cancel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon2)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SphereModelSettingDialog)
        self.cancelButton.clicked.connect(SphereModelSettingDialog.reject)
        self.okButton.clicked.connect(SphereModelSettingDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(SphereModelSettingDialog)
        SphereModelSettingDialog.setTabOrder(self.centerX, self.centerY)
        SphereModelSettingDialog.setTabOrder(self.centerY, self.centerZ)
        SphereModelSettingDialog.setTabOrder(self.centerZ, self.radius)
        SphereModelSettingDialog.setTabOrder(self.radius, self.property)
        SphereModelSettingDialog.setTabOrder(self.property, self.okButton)
        SphereModelSettingDialog.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, SphereModelSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SphereModelSettingDialog.setWindowTitle(_translate("SphereModelSettingDialog", "球体模型参数设置"))
        self.labelUnit.setText(_translate("SphereModelSettingDialog", "单位"))
        self.labelProperty.setText(_translate("SphereModelSettingDialog", "物性"))
        self.label_2.setText(_translate("SphereModelSettingDialog", "中心（Y）"))
        self.label.setText(_translate("SphereModelSettingDialog", "中心（X）"))
        self.label_3.setText(_translate("SphereModelSettingDialog", "中心埋深（Z）"))
        self.label_4.setText(_translate("SphereModelSettingDialog", "半径（R）"))
        self.label_5.setText(_translate("SphereModelSettingDialog", "（z轴向下为正）"))
        self.okButton.setText(_translate("SphereModelSettingDialog", "确定"))
        self.cancelButton.setText(_translate("SphereModelSettingDialog", "取消"))

import UI.UI_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SphereModelSettingDialog = QtWidgets.QDialog()
    ui = Ui_SphereModelSettingDialog()
    ui.setupUi(SphereModelSettingDialog)
    SphereModelSettingDialog.show()
    sys.exit(app.exec_())

